---
abstract: 'Require logged-in user for specified routes'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Dancer2: 0.153000
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Temp: 0.19
  HTTP::Cookies: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0.96
  perl: 5.008001
configure_requires:
  ExtUtils::MakeMaker: 6.17
  perl: 5.008001
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Auth-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer2::Plugin::Auth::Tiny:
    file: lib/Dancer2/Plugin/Auth/Tiny.pm
    version: 0.004
requires:
  Carp: 0
  Dancer2: 0.153000
  Dancer2::Plugin: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny/issues
  homepage: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny
  repository: https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny.git
version: 0.004
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Pedro Melo <melo@simplicidade.org>'
